export type VisualSpec = {
  slug: string;
  reportSlug: string;
  title: string;
  section: string;
  chartType: string;
  layout: string;
  insight: string;
  xAxis?: string;
  yAxis?: string;
  series?: string[];
  supportingMetrics: string[];
};

export const visualSpecs: VisualSpec[] = [
  {
    slug: "nighttime-active-recovery-shift",
    reportSlug: "REPORT-010",
    title: "Nighttime Active-Recovery Shift",
    section: "Chrono-Nutritional Recovery",
    chartType: "Before/After Category Shift",
    layout: "Two-column slope graphic",
    insight: "Reactive sleep products are losing ground to active-recovery rituals anchored in eye health and neurological calm.",
    xAxis: "Nighttime occasions",
    yAxis: "Consumer relevance",
    series: ["Reactive Sleep Aids", "Active Recovery Formats"],
    supportingMetrics: ["66.3% poor sleep prevalence during exams", "20% YoY growth in non-sweet functional liquids"],
  },
  {
    slug: "seven-eleven-cognitive-hub",
    reportSlug: "REPORT-011",
    title: "7-Eleven Cognitive Hub Architecture",
    section: "Shelf Hierarchy",
    chartType: "Shelf Block Diagram",
    layout: "Three-tier retail architecture",
    insight: "The middle shelf now functions as a cognitive bridge that normalizes daily performance beverages.",
    xAxis: "Shelf tiers",
    yAxis: "Consumer entry barrier",
    series: ["Upper Ritual", "Middle Bridge", "Lower Mass"],
    supportingMetrics: ["90% of CVS stores show Brand's 4-SKU vertical blocking", "B-Vitamin row expanded from 2 to 5 SKUs in 12 months"],
  },
  {
    slug: "parent-roi-pivot",
    reportSlug: "REPORT-012",
    title: "Parent Performance ROI Pivot",
    section: "Budget Reallocation",
    chartType: "Budget Shift Bar Chart",
    layout: "Two-bar comparison with annotation",
    insight: "Parents are reallocating discretionary budgets away from leisure toward tutoring and supplement stacks.",
    xAxis: "Household spend category",
    yAxis: "Share of budget shift",
    series: ["Leisure / Travel", "Performance Stacks"],
    supportingMetrics: ["36.4% cut in leisure/travel spend", "72% of parents report high performance anxiety"],
  },
  {
    slug: "ai-audit-claim-heatmap",
    reportSlug: "REPORT-013",
    title: "AI-Audit Claim Heatmap",
    section: "Regulatory Heatmap",
    chartType: "Compliance Heatmap",
    layout: "Risk matrix",
    insight: "Claim language now determines digital survivability, not just legal correctness.",
    xAxis: "Claim territory",
    yAxis: "Audit risk",
    series: ["Red Lines", "Safe Harbors"],
    supportingMetrics: ["AI crawlers verify Ad Licenses on TikTok/Shopee", "Analytical result threshold at 80% of label value"],
  },
  {
    slug: "clean-focus-positioning-gap",
    reportSlug: "REPORT-014",
    title: "Clean-Focus Positioning Gap",
    section: "Whitespace Mapping",
    chartType: "2x2 Positioning Matrix",
    layout: "Outcome vs Experience quadrant",
    insight: "The market is crowded around focus outcomes but nearly empty on the quality of focus experience.",
    xAxis: "Outcome-driven to Experience-driven",
    yAxis: "High stimulation to Sustainable alertness",
    series: ["Mainstream Focus Claims", "Clean-Focus Opportunity"],
    supportingMetrics: ["<5% of retail claims discuss quality of focus", "66.3% of students report poor sleep from stimulant spikes"],
  },
  {
    slug: "zero-sugar-sweetness-reset",
    reportSlug: "REPORT-015",
    title: "Zero-Sugar Sweetness Reset",
    section: "Palate Nudge",
    chartType: "Share Shift Chart",
    layout: "Single-series dominance chart",
    insight: "The student palate reset has made zero-sugar the new default for refrigerated functional launches.",
    xAxis: "Launch type",
    yAxis: "Share of launches",
    series: ["Zero-Sugar", "High-Sugar"],
    supportingMetrics: ["100% of new refrigerated functional launches are zero-sugar", "58% of parents seek sugar-free to avoid hyper-activity"],
  },
  {
    slug: "siam-square-experience-funnel",
    reportSlug: "REPORT-016",
    title: "Siam Square Experience Funnel",
    section: "Experiential Wellness",
    chartType: "Conversion Funnel",
    layout: "Event-to-purchase funnel",
    insight: "Gamified pop-ups convert attention into purchase more effectively than static awareness campaigns.",
    xAxis: "Engagement stage",
    yAxis: "Conversion rate",
    series: ["Audit Participation", "QR Ritual Engagement", "Product Trial"],
    supportingMetrics: ["40% conversion rate after gamified eye-strain audit", "65% engagement with QR 2.0 rituals"],
  },
  {
    slug: "bioharmony-kpi-shift",
    reportSlug: "REPORT-017",
    title: "Bioharmony KPI Shift",
    section: "Wearable Performance Metrics",
    chartType: "Behavior Shift Curve",
    layout: "Two-line cultural shift chart",
    insight: "Students are replacing panic-energy metrics with recovery and readiness scores.",
    xAxis: "Performance mindset",
    yAxis: "Usage intensity",
    series: ["Exam Focus / Energy", "Recovery / Ready Score"],
    supportingMetrics: ["72% of elite students track morning ready scores", "45% growth in sleep-protection behavior vs Red Bull"],
  },
  {
    slug: "pseudo-adhd-crisis-loop",
    reportSlug: "REPORT-018",
    title: "Pseudo-ADHD Crisis Loop",
    section: "Screen-Brain Recovery",
    chartType: "Crisis Loop Diagram",
    layout: "Circular systems graphic",
    insight: "Screen exposure, milestone delay, and parental panic reinforce one another into a new supplement demand engine.",
    xAxis: "Development cycle",
    yAxis: "Escalating intervention need",
    series: ["Screen Exposure", "Milestone Delay", "Parental Panic"],
    supportingMetrics: ["81.6% milestone status", "74.8% expressive language lag"],
  },
  {
    slug: "savory-study-snacks-whitespace",
    reportSlug: "REPORT-019",
    title: "Savory Study Snacks Whitespace",
    section: "Late-Night Satiety",
    chartType: "Retail Adjacency Comparison",
    layout: "Format vs occasion matrix",
    insight: "Savory study broths are taking over the late-night slot previously dominated by instant noodles.",
    xAxis: "Late-night formats",
    yAxis: "Perceived recovery benefit",
    series: ["Instant Noodles", "Functional Broths", "Drinkable Whole-Foods"],
    supportingMetrics: ["30% increase in instant miso facing counts", "45% report noodle fog after midnight snacks"],
  },
  {
    slug: "student-performance-index",
    reportSlug: "REPORT-020",
    title: "Student Performance Index",
    section: "Macro Themes",
    chartType: "Category Evolution Timeline",
    layout: "Three-stage intelligence map",
    insight: "Student performance has evolved from exam panic into a 24/7 performance infrastructure category.",
    xAxis: "Category stage",
    yAxis: "Commercial intensity",
    series: ["Routine Nutrition", "Tactical Performance", "Chrono-Recovery"],
    supportingMetrics: ["100+ signals across 20 dossiers", "$1.49B market size by 2027"],
  },
  {
    slug: "biological-age-revolution",
    reportSlug: "REPORT-021",
    title: "Biological Age Revolution",
    section: "Clinical to Retail Longevity",
    chartType: "Tier Migration Chart",
    layout: "Clinical-to-mass ladder",
    insight: "Biological age testing is migrating from premium clinics toward mainstream retail longevity stacks.",
    xAxis: "Longevity access tier",
    yAxis: "Market accessibility",
    series: ["Clinical Diagnostics", "Premium Programs", "Mass Retail NAD+"],
    supportingMetrics: ["DunedinPACE standardized in major clinics", "NAD+ retail formats moving into mainstream channels"],
  },
  {
    slug: "longevity-tourism-price-arbitrage",
    reportSlug: "REPORT-040",
    title: "Longevity Tourism Price Arbitrage",
    section: "Global Authority",
    chartType: "Price Arbitrage Comparison",
    layout: "Thailand vs West bar chart",
    insight: "Thailand wins the longevity tourism race by combining price advantage, visa flexibility, and longer stays.",
    xAxis: "Treatment market",
    yAxis: "Relative cost / stay value",
    series: ["Thailand", "West"],
    supportingMetrics: ["22-day average stay length", "60% lower costs than Western markets"],
  },
];
